[[redirects]]
  from = "http://zkchat.net"
  to = "https://id.zkchat.net"
  status = 301
  force = true
[[redirects]]
  from = "http://www.zkchat.net"
  to = "https://id.zkchat.net"
  status = 301
  force = true